// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCjdEcSIQ5Luu4GELFm0nMmrL13A25kGQ',
    appId: '1:615975445915:android:98868c7c5a469c230f2d3e',
    messagingSenderId: '615975445915',
    projectId: 'tynenger-82ecd',
    storageBucket: 'tynenger-82ecd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoXhp9zjxEZKdWkfJ1hI5CdhN3ZuMBRg8',
    appId: '1:615975445915:ios:c9c83dfa7c419f480f2d3e',
    messagingSenderId: '615975445915',
    projectId: 'tynenger-82ecd',
    storageBucket: 'tynenger-82ecd.firebasestorage.app',
    iosBundleId: 'com.tyneaung.tynengerFlutterGetxFirebaseChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoXhp9zjxEZKdWkfJ1hI5CdhN3ZuMBRg8',
    appId: '1:615975445915:ios:c9c83dfa7c419f480f2d3e',
    messagingSenderId: '615975445915',
    projectId: 'tynenger-82ecd',
    storageBucket: 'tynenger-82ecd.firebasestorage.app',
    iosBundleId: 'com.tyneaung.tynengerFlutterGetxFirebaseChat',
  );
}
